// src/fields/core/date/View.vue
<template>  
  {{ date }}
</template>

<script setup>
import { inject, computed } from 'vue';
import moment from 'moment';

const repoStore = inject('repoStore', { config: null });

const props = defineProps({
  field: Object,
  value: [String, Number, Boolean, Array, Object],
});

const date = computed(() => {
  if (!props.value) return null;
  
  const defaultInputFormat = props.field.options?.time ? 'YYYY-MM-DDTHH:mm' : 'YYYY-MM-DD';
  const outputFormat = props.field.options?.time ? 'MMM D, YYYY - HH:mm' : 'MMM D, YYYY';
  const inputFormat = props.field.options?.format || defaultInputFormat;
  const dateObject = moment(props.value, inputFormat);
  if (!dateObject.isValid()) {
    console.warn(`Date for field '${props.field.name}' is saved in the wrong format or invalid:`, props.value);
    return '';
  }
  return dateObject.format(outputFormat);
});
</script>

// fields/core/date/view-component.tsx
"use client";
import { parse, format, isValid } from "date-fns";
import { Field } from "@/types/field";
import { CalendarIcon } from "lucide-react";
import { Badge } from "@/components/ui/badge";

const ViewComponent = ({
  value,
  field
}: {
  value: string | string[],
  field: Field
}) => {
  if (!value) return null;

  const firstValue = Array.isArray(value) ? value[0] : value;
  if (firstValue == null) return null;
  const extraValuesCount = Array.isArray(value) ? value.length - 1 : 0;
  const inputFormat = field.options?.time ? "yyyy-MM-dd'T'HH:mm" : "yyyy-MM-dd";
  const outputFormat = field.options?.time ? "MMM d, yyyy - HH:mm" : "MMM d, yyyy";

  const formatDate = (date: string) => {
    const parsedDate = parse(date, inputFormat, new Date());
    if (!isValid(parsedDate)) {
      console.warn(`Date for field '${field.name}' is saved in the wrong format or invalid: ${date}.`);
      return null;
    }
    return format(parsedDate, outputFormat);
  };
  
  return (
    <span className="flex items-center gap-x-1.5">
      <Badge variant="secondary">
        <CalendarIcon/>
        {formatDate(firstValue)}
      </Badge>
      {extraValuesCount > 0 && (
        <Badge variant="secondary" className="px-1">
          +{extraValuesCount}
        </Badge>
      )}
    </span>
  );
}

export { ViewComponent };
